apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: sample-app
  labels:
        app: "example"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: example
  selector:
    app: "example"
  type: ClusterIP

