{{- if and .Values.rbac.create (eq .Values.clusterRole.create false) -}}
{{- range $namespace := (append .Values.allowedNamespaces .Release.Namespace) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders-role
  namespace: {{ $namespace }}
  labels:
    app: kubeinvaders
    chart: {{ template "kubeinvaders.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders-rolebinding
  namespace: {{ $namespace }}
  labels:
    app: kubeinvaders
    chart: {{ template "kubeinvaders.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeinvaders.serviceAccountName" $ }}
  namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: kubeinvaders-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
