apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{ template "kubeinvaders.serviceAccountName" . }}
  labels:
    app: {{ template "kubeinvaders.name" . }}
    chart: {{ template "kubeinvaders.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
